spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estore
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true